dist: trusty
sudo: false
addons:
  apt:
    packages:
      - check
      # This one is only needed for ARCH=i386, but we can't add conditional
      # package dependencies in this section
      - check:i386
      - gcc-multilib

language: c
compiler:
  - clang
  - gcc
env:
  - ARCH=i386
  - ARCH=amd64
  - ARCH=i386 ENABLE_SHARED_TESTS=YES
  - ARCH=amd64 ENABLE_SHARED_TESTS=YES
  - ARCH=i386 FALLBACK_U128=YES
  - ARCH=amd64 FALLBACK_U128=YES
os:
  - linux
  # TODO(dcreager): Reenable this once the Travis Mac backlog isn't quite so
  # horrific.
  # - osx
install: .travis/install
script: .travis/test

# In addition to pull requests, always build these branches
branches:
  only:
    - master
