dist: trusty
sudo: false
addons:
  apt:
    packages:
      - check
      # This one is only needed for ARCH=i386, but we can't add conditional
      # package dependencies in this section
      - check:i386
      - gcc-multilib
      - valgrind

language: c
compiler:
  - clang
  - gcc
env:
  - ARCH=i386  FLAVOR=autotools
  - ARCH=amd64 FLAVOR=autotools
  - ARCH=i386  FLAVOR=cmake
  - ARCH=amd64 FLAVOR=cmake
  - ARCH=i386  FLAVOR=shared-cmake
  - ARCH=amd64 FLAVOR=shared-cmake
  - ARCH=i386  FLAVOR=fallback-u128
  - ARCH=amd64 FLAVOR=fallback-u128
  - ARCH=i386  FLAVOR=cmake-from-dist
  - ARCH=amd64 FLAVOR=cmake-from-dist
os:
  - linux
  # TODO(dcreager): Reenable this once the Travis Mac backlog isn't quite so
  # horrific.
  # - osx
install: .travis/install
script: .travis/test

# In addition to pull requests, always build these branches
branches:
  only:
    - master
